// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv5la7cUhPJmhJYWAAjkcqvqmWmCwmKk0',
    appId: '1:859118364242:web:00b63a9c4bbd3fc45e218b',
    messagingSenderId: '859118364242',
    projectId: 'pfe-project-database',
    authDomain: 'pfe-project-database.firebaseapp.com',
    storageBucket: 'pfe-project-database.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_A_kXRgPN3dQrfjRIbMT0rO2KeX3cQ8c',
    appId: '1:859118364242:android:e2d15a0b1da040635e218b',
    messagingSenderId: '859118364242',
    projectId: 'pfe-project-database',
    storageBucket: 'pfe-project-database.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQCkcnDmbcptx-4i70czsyuNi9qZKTbVo',
    appId: '1:859118364242:ios:4c83f8327f648eec5e218b',
    messagingSenderId: '859118364242',
    projectId: 'pfe-project-database',
    storageBucket: 'pfe-project-database.appspot.com',
    iosClientId: '859118364242-tgnhn3vb6paek54noafpoinqkv78m8i7.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectPfe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQCkcnDmbcptx-4i70czsyuNi9qZKTbVo',
    appId: '1:859118364242:ios:4c83f8327f648eec5e218b',
    messagingSenderId: '859118364242',
    projectId: 'pfe-project-database',
    storageBucket: 'pfe-project-database.appspot.com',
    iosClientId: '859118364242-tgnhn3vb6paek54noafpoinqkv78m8i7.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectPfe',
  );
}
